/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package byui.cit260.TGSBgame.model;

/**
 *
 * @author Adriana
 */
public enum Scene {
    
    JFK_Airport("\n"
            + "\n--------------------------------------------------"
            + "\n| JFK Airport                                    |"
            + "\n--------------------------------------------------"
            + "\nYou have arrived at the John F Kennedy Airport    "
            + "\n(JFK) is the busiest of New York's three airport. "
            + "\nthree airports There are millions of passengers   "
            + "\nheading to or arriving from domestic and interna- "
            + "\ntional destinations every year here. Today is a   "
            + "\nbeautiful day, and there are many people passing  "
            + "\nby, some in a hurry and some looking for someone  "
            + "\nto who could guide them out of this madness. You  "
            + "\nran to get into one of the AirTrain and is heading"
            + "\nout to your hotel. A person next to you engages in"
            + "\na conversation."
            + "\n--------------------------------------------------"),
    
    Time_Square("\n"
            + "\n----------------------------------------------------"
            + "\n| Time Square                                      |"
            + "\n----------------------------------------------------"
            + "\nTimes Square displays of lights and digital signs   "
            + "\nis impressive even during the daytime. It is a      "
            + "\nmajor commercial intersection and neighborhood in   "
            + "\nMidtown Manhattan, New York City, at the junction   "
            + "\nof Broadway and Seventh Avenue. There are people    "
            + "\neverywhere, some enjoying the day eating ouside,    "
            + "\nothers are in line to by tickes for tonight's       "
            + "\nshows other's are waiting for the free entertainment"
            + "\nabout to start, and others are just trying to take  "
            + "\nall in as you do. As you watch people passing by, a "
            + "\nperson stops by your side and starts a conversation."
            + "\n----------------------------------------------------"),
    
    Central_Park("\n"
            + "\n----------------------------------------------------"
            + "\n| Central Park                                     |"
            + "\n----------------------------------------------------"
            + "\nYou find yourself walking into Central Park, the    "
            + "famous urban park in the central part of Manhattan. In"
            + "this beautiful, sunny, warm day, the park offers a    "
            + "cool and quite place to sit and enjoy the beautiful   "
            + "scene. There are people everywhere sitting on benches,"
            + " in the grass, and in the half-walls by the sidewalks."
            + " As you are sitting on the wall, a person nearby      "
            + "strikes a conversation.                               "
            + "\n----------------------------------------------------"),
    
    NY_Subway("\n"
            + "\n----------------------------------------------------"
            + "\n| NYC Subway                                       |"
            + "\n----------------------------------------------------"
            + "\nYou are about to enter the New York City Subway. It "
            + "is the largest, by number of stations, and one of the "
            + "world's oldest, most used public transit systems.     "
            + "Thousands of people travel in them daily. New Yorkers "
            + "are not famous for neighbourly conversation. However, "
            + "a nearby passenger starts to talk to you.             "
            + "\n----------------------------------------------------"),
    
    Chinatown("\n"
            + "\n----------------------------------------------------"
            + "\n| Chinatown                                        |"
            + "\n----------------------------------------------------"
            + "\nChinatown is a neighborhood in Manhattan that is    "
            + "home to the largest enclave of Chinese people in the  "
            + "Western Hemisphere. It looks, feels and smells        "
            + "different. The Chinese culture is present in every    "
            + "aspect, from the number of people walking on the      "
            + "street, to the open market feel of food and products  "
            + "sold on the sidelines. Even the trafic signs are      "
            + "written in both Chinese and English. It is a foreign  "
            + "experience in the middle of lower Manhathan.          "
            + "\n----------------------------------------------------"),
    
    Little_Italy("\n"
            + "\n----------------------------------------------------"
            + "\n| Little Italy                                     |"
            + "\n----------------------------------------------------"
            + "\nLittle Italy is a neighborhood in lower Manhattan,  "
            + "once known for its large population of Italians.      "
            + "Today the neighborhood consists of only a few Italian "
            + "stores and restaurants. Little Italy residents have   "
            + "seen organized crime since the early 1900s. Powerful  "
            + "members of the Italian Mafia operated in Little Italy."
            + " But that is not the case anymore. So when a stranger "
            + "approches, you don't feel too anxious.                "
            + "\n----------------------------------------------------"),
    
    Metropolitan_Museum_of_Art("\n"
            + "\n-----------------------------------------------------"
            + "\n| Metropolitan Museum of Art                        |"
            + "\n-----------------------------------------------------"
            + "\nThe Metropolitan Museum of Art is the largest art    "
            + "museum in the United States and one of the ten largest "
            + "in the world. Its permanent collection contains more   "
            + "than two million works. Represented in the permanent   "
            + "collection are works of art from classical antiquity   "
            + "and Ancient Egypt, paintings and sculptures from b     "
            + "nearly all the European masters, and an extensive      "
            + "collection of American and modern art. The Met also    "
            + "maintains extensive holdings of African, Asian,        "
            + "Oceanic, Byzantine, and Islamic art. After afew minutes"
            + " observing the art, a nearby observer aproches and     "
            + "quietly begins to speak.                               "
            + "\n-----------------------------------------------------"),
    
    Broadway("\n"
            + "\n-----------------------------------------------------"
            + "\n| Broadway                                          |"
            + "\n-----------------------------------------------------"
            + "\nBroadway is widely known as the heart of the American"
            + " theater industry, and also refers to the theatrical   "
            + "performances presented in the 40 professional theaters "
            + "with 500 or more seats. I is located in the Theater    "
            + "District and Lincoln Center along Brodway. It          "
            + "influences popular culture and helps New York City be  "
            + "the cultural capital of the nation. While in line to   "
            + "buy tickets, the person behind you starts talking to   "
            + "you."
            + "\n----------------------------------------------------"),
    
    Lincoln_Center("\n"
            + "\n----------------------------------------------------"
            + "\n| Lincoln Center                                   |"
            + "\n----------------------------------------------------"
            + "\nThe Lincoln Center of Performing Arts is a complex  "
            + "of several buildings. The center of the plaza has 30  "
            + "indoor and outdoor performance facilities. One of the "
            + "eleven residential organizations serves three primary "
            + "roles: presents artistic programming, is the national "
            + "leader in arts, education, and community relations,   "
            + "along with managing the center's campus. As the       "
            + "world's largest presenter of performing arts, offering"
            + "some 5,000 programs, initiatives and events as the    "
            + "Emmy Award.                                           "
            + "\n----------------------------------------------------"),
    
    Grand_Central_Station("\n"
            + "\n------------------------------------------------------"
            + "\n| Grand Central Station                              |"
            + "\n------------------------------------------------------"
            + "\nGrand Central Station is a commuter railroad terminal "
            + " in Midtown Manhattan. It covers 48 acres, has 44 "
            + "platforms, more than any other railroad station in the  "
            + "world. Features both monumental and meticulously        "
            + "crafted detail, historian David Cannadine described     "
            + "it one of the most majestic buildings of the twentieth  "
            + " century. It's the sixth-most-visited tourist attraction"
            + " for its roughly 21.6 million annual visitors.          "
            + "\n------------------------------------------------------"),
    
    Statue_of_Liberty("\n"
            + "\n-----------------------------------------------------"
            + "\n| Statue of Liberty                                 |"
            + "\n-----------------------------------------------------"
            + "\nThe Statue of Liberty is a colossal neoclassical     "
            + "sculpture on Liberty Island in New York Harbor. The    "
            + "statue is an icon of the United States and its freedom,"
            + " and was a welcoming sight to immigrants arriving from "
            + "abroad. Seeing it in person is a memorable experience. "
            + "\n-----------------------------------------------------"),
    
    Hudson_River("\n"
            + "\n----------------------------------------------------"
            + "\n| Hudson River                                     |"
            + "\n----------------------------------------------------"
            + "\nThe Hudson River flows north to south and eventually"
            + "drains into the Atlantic Ocean, between New York City "
            + "and Jersey City. The Hudson River has been a vital    "
            + "artery in New York's history, an essential tool for   "
            + "travel, transport, survival and inspiration for       "
            + "generations. It provides an amazing view. The sun     "
            + "seems to rest on the sparkling river, allowing you to "
            + "fully appreciate Manhattan Island.                    "
            + "\n----------------------------------------------------"),
    
    Chelsea_Market("\n"
            + "\n----------------------------------------------------"
            + "\n| Chelsea Market                                   |"
            + "\n----------------------------------------------------"
            + "\nThe Chelsea Market is an enclosed urban food court, "
            + "shopping mall, and office building in the Chelsea     "
            + "neighborhood of Manhattan. This unique place's shops  "
            + "and restaurants give you vast selections of goods.    "
            + "Great eateries and historic buildings surround you.   "
            + "You're granted easy access to Highline Park. Nature's "
            + "plant life calls for attention, splashes of color     "
            + "springing up everywhere you look. At this point, it   "
            + "feels like your in a world seperate from New York.    "
            + "\n----------------------------------------------------"),
    
    Brooklyn_Bridge("\n"
            + "\n-----------------------------------------------------"
            + "\n| Brooklyn Bridge                                   |"
            + "\n-----------------------------------------------------"
            + "\nOne of the oldest bridges in New York is the Brooklyn"
            + "Birdge. Walking on this bridge from Brooklyn to        "
            + "Manhattan is very pleasureable. Loads of photo         "
            + "opportunities and views are presented throughout you're"
            + "walk. Brooklyn bridge is and has been an engineering   "
            + "marvel for ages. Smiling faces, laughter and joy       "
            + "surround you, and you can't help but take part in that."
            + "\n-----------------------------------------------------"),
    
    Soho("\n"
            + "\n------------------------------------------------------"
            + "\n| Soho                                               |"
            + "\n------------------------------------------------------"
            + "\nSoho refers to the area being South of Houston Street."
            + "Soho is the welcome home for high end shopping, cool    "
            + "restaurants,  and maybe even a little celebrity-gawking."
            + "The area's history is an archetypal example of          "
            + "inner-city regeneration, which includes the SoHo-Cast   "
            + "Iron Historic District. SoHo is known for its           "
            + "commercialization and eclectic mix of shopping          "
            + "boutiques.                                              "
            + "\n------------------------------------------------------"),
    
    Empire_State_Building("\n"
            + "\n----------------------------------------------------"
            + "\n| Empire State Building                            |"
            + "\n----------------------------------------------------"
            + "\nThe Empire State Building is generally thought of as"
            + " an American cultural icon. It is designed in the     "
            + "distinctive Art Deco style and has been named as one  "
            + "of the Seven Wonders of the Modern World. Paying      "
            + "attention to the decor, enlarged photographs and      "
            + "articles, you make your way to the breath-taking      "
            + "view on the sky deck. There is a lot of history to    "
            + "be absorbed through these, the whole feel of it adding"
            + "to the romantic view of NYC. The observation deck is  "
            + "breathtaking.                                         "
            + "\n----------------------------------------------------"),
    Rockefeller_Center("\n"
            + "\n----------------------------------------------------"
            + "\n| Rockefeller Center                               |"
            + "\n----------------------------------------------------"
            + "\nYou're standing at the top of the Rock at "
            + "Rockefeller Center in the G.E. Building.  Incredible   "
            + "views of Central Park and the island expose themselves."
            + "Some say the best sightseeing in NY is right in front "
            + "of you. Outside is the famous ice skating rink and "
            + "Christmas tree in the winter. Unusual, unexpected and "
            + "always exciting, Rockefeller Center is home to some of"
            + "New York City's most spectacular, talked-about events."
            + "\n----------------------------------------------------"),
    Ellis_Island("\n"
            + "\n----------------------------------------------------"
            + "\n| Ellis Island                                     |"
            + "\n----------------------------------------------------"
            + "\nEllis Island was the gateway for millions of        "
            + "immigrants to get into the United States. As the      "
            + "nation's busiest immigrant inspection station from    "
            + "1892 until 1954, the Main Building now houses the     "
            + "Immigration Museum. A Wall of Honor rests outside the "
            + "main building, containing a partial list of immigrants"
            + "processed on the island.                              "
            + "\n----------------------------------------------------"),
    
    New_York_Public_Library("\n"
            + "\n----------------------------------------------------"
            + "\n| New York Public Library                          |"
            + "\n----------------------------------------------------"
            + "\nThe New York Public Library is a public library     "
            + "system in New York City. With nearly 53 million items,"
            + " the New York Public Library is the second largest    "
            + "public library in the United States (behind the       "
            + "Library of Congress), and fourth largest in the world."
            + " A magnificent example of Beaux-Arts style of         "
            + "architecture, this library has symbolized the         "
            + "democratic ideal of free and open access to knowledge "
            + "since it opened to the public in 1911. Patience and   "
            + "Fortitude, the world-renowned pair of marble lions    "
            + "that stand proudly before the majestic Beaux-Arts     "
            + "building, await you as you enter the building.        "
            + "\n----------------------------------------------------"),
    
    Fifth_Avenue("\n"
            + "\n----------------------------------------------------"
            + "\n| Fifth Avenue                                     |"
            + "\n----------------------------------------------------"
            + "\nFith Avenue is best known as an unrivaled shopping  "
            + "street. Almost any upscale retailer has a prestigious "
            + "store located on this street. It is considered among  "
            + "the most expensive and best shopping streets in the   "
            + "world.This is one of the key streets that define New  "
            + "York City. If you like window shopping, this is the   "
            + "place you go. If you have money you will like it even "
            + "more. The street is busy with bustling people flowing "
            + "in and out of the stores.                             "
            + "\n----------------------------------------------------"),
    
    Gothan_West_Market("\n"
            + "\n----------------------------------------------------"
            + "\n| Gothan West Market                               |"
            + "\n----------------------------------------------------"
            + "\nGothan West Market is a unique eating destination in"
            + "New York. It is the first-of-its-kind day & night     "
            + "market dining destination in Hell's Kitchen. The food "
            + " court style and inconvenient address proves that     "
            + "people going there are seeking for this new eating    "
            + "adventure. A sign in one of the business recently     "
            + "said: When was the last time you did something for    "
            + "the first time?                                       "
            + "\n----------------------------------------------------"),
    Washignton_Square_Park("\n"
            + "\n----------------------------------------------------"
            + "\n| Washignton Square Park                           |"
            + "\n----------------------------------------------------"
            + "\nWashington Square Park is a landmark in Manhattan.  "
            + "Located in the neighborhood of Greenwich Village, it  "
            + "is as a meeting place and a center for cultural       "
            + "activity. It is also known as a parade ground, a      "
            + "gathering spot for avant-garde artists, a battleground"
            + "for chess enthusiasts, as well as a playground for    "
            + "children and canines. It is always full of life with  "
            + "street performers and people lounging.                "
            + "\n----------------------------------------------------"),
    
    Flatiron_Building("\n"
            + "\n------------------------------------------------------"
            + "\n| Flatiron Building                                  |"
            + "\n------------------------------------------------------"
            + "\nThe Flatiron Building is considered to be a           "
            + "groundbreaking skyscraper. It is located at 175 Fift    "
            + " Avenue in the borough of Manhattan, New York City.     "
            + "Marvel has used many of its architecture as inspiration "
            + "for location of its scenerios. It's a beautiful bulding."
            + "People go there to appreciate the architecture and      "
            + "lunch in the park accros the street. Currently, it is   "
            + "an office building containing offices for small and     "
            + "medium sized companies.                                 "
            + "\n------------------------------------------------------"),
    
    Wall_Street("\n"
            + "\n----------------------------------------------------"
            + "\n| Wall Street                                      |"
            + "\n----------------------------------------------------"
            + "\nOver time, the term Wall Street has become a metonym"
            + "for the financial markets of the United States as a   "
            + "whole. It's also the American financial sector ,even  "
            + "if financial firms are not physically located there,  "
            + "and signifies New York-based financial interests. It  "
            + "has a conotation of power and money. The movie Wall   "
            + "Street exemplifies the image this area came to        "
            + "symbolize. From there you can walk to trinity church, "
            + "which is a very contrasting image and feel for the    "
            + "whole area.                                           "
            + "\n----------------------------------------------------"),
    
    Queensbridge_Park_Queens("\n"
            + "\n----------------------------------------------------"
            + "\n| Queensbridge Park Queens                         |"
            + "\n----------------------------------------------------"
            + "\nQueensbridge Park is a beautiful park with mature   "
            + "trees, ball fields, and plenty of families barbecuing "
            + "on weekends. It also has a nice paved walkway along   "
            + "the East River with great views of the Queensboro     "
            + "Bridge, Roosevelt Island, midtown Manhattan and the   "
            + "Freedom Tower in the distance.This park is named for  "
            + "the nearby Queensboro Bridge. From there, there are   "
            + "spectacular views of 59th Street bridge, Chrysler     "
            + "Building, Empire State Building, and more. It provides"
            + "a very good place to admire NY from a close distance. "
            + "\n----------------------------------------------------"),
    
    Music_Hall_of_Williamsburg_Brooklyn("\n"
            + "\n-----------------------------------------------------"
            + "\n| Music Hall of Williamsburg Brooklyn               |"
            + "\n-----------------------------------------------------"
            + "\nThe Music Hall of Williamsburg is a venue located at "
            + "66 North 6th Street in the Williamsburg neighborhood of"
            + "Brooklyn. The venue has a capacity of 550 people and   "
            + "has shows on most nights of the week.  Indie-rock fans "
            + "groove to live music at this popular triple-tiered     "
            + "club that offer three bars on location.                "
            + "\n-----------------------------------------------------"),
            
    
    Carlos_Bakery_New_Jersey("\n"
            + "\n------------------------------------------------------"
            + "\n| Carlos Bakery New Jersey                           |"
            + "\n------------------------------------------------------"
            + "\nCarlo's is a family owned bakery featured on Cake     "
            + "Boss. It is known for its delicious pastries, desserts  "
            + "& cakes. Master Baker, Bartolo Jr. “Buddy”, has been     "
            + "featured in numerous publications,and his cake was voted"
            + "by the Today’s Show viewers as best cake in America.    "
            + "\n-----------------------------------------------------"),
    
    Radio_City_Music_Hall("\n"
            + "\n----------------------------------------------------"
            + "\n| Radio City Music Hall                            |"
            + "\n----------------------------------------------------"
            + "\nRadio City Music Hall is an entertainment venue     "
            + "located in Rockefeller Center. Its nickname is the    "
            + "Showplace of the Nation, and for a time it was the    "
            + "leading tourist destination in the city. people go    "
            + "there to watch world famous performances and to enjoy "
            + "the beautifuly decorated location. It is famous for   "
            + "the Spectacular with the Rockettes. It is quite an    "
            + "opulent treat to visit.                               "
            + "\n----------------------------------------------------"),
    
    The_Cathedral_Church_of_St_John_the_Divine("\n"
            + "\n-----------------------------------------------------"
            + "\n| The Cathedral Church of St John the Divine        |"
            + "\n-----------------------------------------------------"
            + "\nThere is a dispute about whether the Cathedral church"
            + " of St. John, the Divine, or  the Liverpool Cathedral  "
            + "is the world's largest Anglican cathedral existing     "
            + "today. This immense and historic church is known for   "
            + "its concerts, Sunday service & annual blessing of      "
            + "animals. The adjacent Peace Garden is one of the most  "
            + "whimsical places in the city.                          "
            + "\n-----------------------------------------------------"),
    
    United_Nation_Headquarters("\n"
            + "\n----------------------------------------------------"
            + "\n| United Nation Headquarters                       |"
            + "\n----------------------------------------------------"
            + "\nThe United Nations Headquarters is located in the   "
            + "heart of New York City . This 18-acre site has been   "
            + "declared international territory and belongs to the   "
            + "193 Member States of the United Nations. It was       "
            + "founded in 1945 after the Second World War by 51      "
            + "countries committed to maintaining international      "
            + "peace and security, developing friendly relations     "
            + "among nations and promoting social progress, better   "
            + "living standards and human rights.                    "
            + "\n----------------------------------------------------"),
    Unisphere_Queens("\n"
            + "\n-----------------------------------------------------"
            + "\n| Unisphere Queens                                  |"
            + "\n-----------------------------------------------------"
            + "\nThe Unisphere is a 12-story high, spherical stainless"
            + "steel representation of the Earth.The unofficial symbol"
            + "of Queens, it exists as one of the few remaining "
            + "artifacts from the 1964-65 New York World's Fair. Three"
            + "rings circle the globe, representing the orbits of the "
            + "first American astronaut, the first Russian cosmonaut  "
            + "and the first communications satellite to orbit the"
            + "Earth."
            + "\n----------------------------------------------------"),
    Yankee_Stadium_Bronx("\n"
            + "\n----------------------------------------------------"
            + "\n| Yankee Stadium Bronx                             |"
            + "\n----------------------------------------------------"
            + "\nYankee Stadium is a stadium located in the Bronx. It"
            + "is the home ballpark for the New York Yankees of Major"
            + "League Baseball and the home stadium for New York City"
            + "FC of Major League Soccer. People are impressed with  "
            + "this new structure even with the historical landmarks "
            + "around to compare. It is great place to visit if you  "
            + "enjoy baseball.                                       "
            + "\n----------------------------------------------------"),
    
    Nine_Eleven_Museum("\n"
            + "\n------------------------------------------------------"
            + "\n| 9-11 Museum                                        |"
            + "\n----------------------------------------------------- "
            + "\nThe National September 11 Memorial & Museum is the    "
            + "principal memorial and museum, respectively             "
            + "commemorating the September 11 attacks of 2001 and the  "
            + "World Trade Center bombing of 1993. The Museum displays "
            + " artifacts associated with the events of 9/11, while its"
            + " mission is to honor the memories of those killed on    "
            + "9/11 and educate future generations. It was created as  "
            + " a tribute the victims and the families.                "
            + "\n------------------------------------------------------"),
    
    High_Line("\n"
            + "\n----------------------------------------------------"
            + "\n| High Line                                        |"
            + "\n----------------------------------------------------"
            + "\nThe High Line Park in Manhattan was built on an     "
            + "elevated section of a disused New York Central        "
            + "Railroad spur called the West Side Line. It stands 30 "
            + "feet above street level on an old rail line,          "
            + "fantastically reclaiming the disused piece of         "
            + "infrastructure. The beautiful design is now a park    "
            + "where you can take in the serenity and some pretty    "
            + "amazing city views.                                   "
            + "\n----------------------------------------------------"),
    
    Manhatan_Temple("\n"
            + "\n----------------------------------------------------"
            + "\n| Manhathan Temple                                 |"
            + "\n----------------------------------------------------"
            + "\nYou arrived in front of the LDS Manhattan Temple.   "
            + "You cannot believe that a temple can be located in the"
            + "middle of the hussle and bussle of a city like New    "
            + "York. You can see it almost immediately as you come   "
            + "out of the subway. It is located at the intersection  "
            + "of West 65th Street, Broadway, and Columbus Avenue.   "
            + "The temple stands among some of New York City's most  "
            + "prominent landmarks including the Lincoln Center, and "
            + "Central Park a walking distance away. As you stand in "
            + "the little plaza in front of the temple to contemplate"
            + "its beauty and significance, a pedestrian approaches  "
            + "you and asks a question.                              "
            + "\n----------------------------------------------------");
    
    private final String description;
        
    Scene(String description) {
        this.description = description;
    }

    @Override
    public String toString() {
        return this.description;
    }
    
    
}
